[package]
name = "tms"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { workspace = true }
async-graphql = { workspace = true }
sqlx = { workspace = true }
rstest = { workspace = true }
validator = { workspace = true }
serde = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
sea-query = { workspace = true }
serde_json = { workspace = true }
auth = { path = "../auth" }
