/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export enum CrmCampaignContactsStatus {
  CLICKED = "clicked",
  OPENED = "opened",
  RESPONDED = "responded",
  SENT = "sent",
  UNSUBSCRIBE = "unsubscribe",
}

export enum CrmCampaignStatus {
  ACTIVE = "active",
  COMPLETED = "completed",
  PAUSED = "paused",
  PLANNED = "planned",
}

export enum CrmCasePriority {
  CRITICAL = "critical",
  HIGH = "high",
  LOW = "low",
  MEDIUM = "medium",
}

export enum CrmCaseStatus {
  CLOSED = "closed",
  IN_PROGRESS = "in_progress",
  OPEN = "open",
  PENDING_CUSTOMER = "pending_customer",
}

export enum CrmContactStatus {
  CUSTOMER = "customer",
  INACTIVE = "inactive",
  LEAD = "lead",
  PROSPECT = "prospect",
}

export enum CrmInteractionType {
  CALL = "call",
  CHAT = "chat",
  EMAIL = "email",
  MEETING = "meeting",
  NOTE = "note",
}

export enum CrmInvoiceStatus {
  CANCELLED = "cancelled",
  DRAFT = "draft",
  OVERDUE = "overdue",
  PAID = "paid",
  SENT = "sent",
}

export enum CrmLeadStatus {
  CONTACTED = "contacted",
  NEW = "new",
  QUALIFIED = "qualified",
  UNQUALIFIED = "unqualified",
}

export enum CrmNotificationChannel {
  EMAIL = "email",
  PUSH = "push",
  SMS = "sms",
  WEBHOOK = "webhook",
}

export enum CrmNotificationDeliveryStatus {
  BOUNCED = "bounced",
  DELIVERED = "delivered",
  FAILED = "failed",
  PENDING = "pending",
  SENT = "sent",
}

export enum CrmNotificationType {
  DELAYED = "delayed",
  DELIVERED = "delivered",
  EXCEPTION = "exception",
  IN_TRANSIT = "in_transit",
  OUT_FOR_DELIVERY = "out_for_delivery",
  PICKUP_SCHEDULED = "pickup_scheduled",
}

export enum CrmOpportunityStage {
  CLOSED_LOST = "closed-lost",
  CLOSED_WON = "closed-won",
  PROPOSAL = "proposal",
  PROSPECTING = "prospecting",
  QUALIFICATION = "qualification",
}

export enum LmsAddressType {
  BILLING = "billing",
  OFFICE = "office",
  SHIPPING = "shipping",
  WAREHOUSE = "warehouse",
}

export enum LmsDeliveryStatus {
  ATTEMPTED = "attempted",
  DELIVERED = "delivered",
  FAILED = "failed",
  PENDING = "pending",
  RESCHEDULED = "rescheduled",
}

export enum LmsLegStatus {
  CANCELLED = "cancelled",
  COMPLETED = "completed",
  IN_PROGRESS = "in_progress",
  PLANNED = "planned",
}

export enum LmsPackageType {
  BAG = "bag",
  BOX = "box",
  CRATE = "crate",
  ENVELOPE = "envelope",
  PALLET = "pallet",
  TUBE = "tube",
}

export enum LmsPerformanceMetricType {
  COST_EFFICIENCY = "cost_efficiency",
  CUSTOMER_SATISFACTION = "customer_satisfaction",
  DAMAGE_RATE = "damage_rate",
  ON_TIME_DELIVERY = "on_time_delivery",
}

export enum LmsProviderInvoiceStatus {
  CANCELLED = "cancelled",
  DRAFT = "draft",
  OVERDUE = "overdue",
  PAID = "paid",
  SENT = "sent",
}

export enum LmsProviderType {
  COURIER = "courier",
  EXPRESS = "express",
  FREIGHT = "freight",
  FTL = "ftl",
  LTL = "ltl",
  POSTAL = "postal",
}

export enum LmsRouteStatus {
  CANCELLED = "cancelled",
  COMPLETED = "completed",
  IN_PROGRESS = "in_progress",
  PLANNED = "planned",
}

export enum LmsServiceType {
  ECONOMY = "economy",
  EXPRESS = "express",
  FREIGHT = "freight",
  OVERNIGHT = "overnight",
  STANDARD = "standard",
}

export enum LmsShipmentStatus {
  CANCELLED = "cancelled",
  CREATED = "created",
  DELIVERED = "delivered",
  EXCEPTION = "exception",
  IN_TRANSIT = "in_transit",
  OUT_FOR_DELIVERY = "out_for_delivery",
  PICKED_UP = "picked_up",
}

export enum LmsTrackingEventType {
  ARRIVED = "arrived",
  CANCELLED = "cancelled",
  CREATED = "created",
  DELIVERED = "delivered",
  DEPARTED = "departed",
  EXCEPTION = "exception",
  OUT_FOR_DELIVERY = "out-for-delivery",
  PICKED_UP = "picked_up",
}

export enum LmsTransportLegType {
  DELIVERY = "delivery",
  LINEHAUL = "linehaul",
  PICKUP = "pickup",
  TRANSFER = "transfer",
}

export enum LmsTransportMode {
  AIR = "air",
  RAIL = "rail",
  ROAD = "road",
  SEA = "sea",
}

export enum LmsWarehouseInventoryStatus {
  PICKED = "picked",
  RECEIVED = "received",
  SHIPPED = "shipped",
  STORED = "stored",
}

export enum LmsWarehouseType {
  BONDED = "bonded",
  COLD_STORAGE = "cold_storage",
  CROSS_DOCK = "cross_dock",
  DISTRIBUTION = "distribution",
  FULFILLMENT = "fulfillment",
}

export enum OrgPermissionActions {
  DELETE = "delete",
  READ = "read",
  SELECT = "select",
  UPDATE = "update",
}

export enum TmsDriverStatus {
  ACTIVE = "active",
  INACTIVE = "inactive",
  ON_LEAVE = "on-leave",
  TERMINATED = "terminated",
}

export enum TmsVehicleStatus {
  ACTIVE = "active",
  MAINTENANCE = "maintenance",
  OUT_OF_SERVICE = "out-of-service",
  RETIRED = "retired",
}

export enum TmsVehicleType {
  CAR = "car",
  MOTORCYCLE = "motorcycle",
  TRAILER = "trailer",
  TRUCK = "truck",
  VAN = "van",
}

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface _SqlxMigrations {
  checksum: Buffer;
  description: string;
  executionTime: Int8;
  installedOn: Generated<Timestamp>;
  success: boolean;
  version: Int8;
}

export interface AuthAccounts {
  /**
   * Access token issued by the provider, if applicable.
   */
  accessToken: string | null;
  /**
   * Expiration timestamp for the access token.
   */
  accessTokenExpiresAt: Timestamp | null;
  /**
   * Provider-specific account identifier (e.g., subject/user id at the provider).
   */
  accountId: string;
  /**
   * Row creation timestamp (UTC).
   */
  createdAt: Generated<Timestamp>;
  /**
   * Primary key: UUID for the account linkage record.
   */
  id: Generated<string>;
  /**
   * ID token (JWT) returned by the provider, if applicable.
   */
  idToken: string | null;
  /**
   * Password hash for local credentials (if using email+password).
   */
  password: string | null;
  /**
   * Identifier for the identity provider (e.g., google, github, email).
   */
  providerId: string;
  /**
   * Refresh token issued by the provider, if applicable.
   */
  refreshToken: string | null;
  /**
   * Expiration timestamp for the refresh token.
   */
  refreshTokenExpiresAt: Timestamp | null;
  /**
   * Scopes granted for the tokens (space- or comma-separated).
   */
  scope: string | null;
  /**
   * Row last-updated timestamp (UTC).
   */
  updatedAt: Generated<Timestamp>;
  /**
   * FK to auth.users(id) that owns this account linkage.
   */
  userId: string;
}

export interface AuthSessions {
  /**
   * Row creation timestamp (UTC).
   */
  createdAt: Generated<Timestamp>;
  /**
   * When the session becomes invalid and will no longer be accepted.
   */
  expiresAt: Timestamp;
  /**
   * Primary key: UUID for the session record.
   */
  id: Generated<string>;
  /**
   * Last seen IP address for the session (if available).
   */
  ipAddress: string | null;
  /**
   * Opaque, unique session token.
   */
  token: string;
  /**
   * Row last-updated timestamp (UTC).
   */
  updatedAt: Generated<Timestamp>;
  /**
   * User agent string from the client (if available).
   */
  userAgent: string | null;
  /**
   * FK to auth.users(id) indicating the session owner.
   */
  userId: string;
}

export interface AuthUsers {
  /**
   * Row creation timestamp (UTC).
   */
  createdAt: Generated<Timestamp>;
  /**
   * Unique email address for the user.
   */
  email: string;
  /**
   * Timestamp when the email address was verified; null if not verified.
   */
  emailVerified: Timestamp | null;
  /**
   * Primary key: stable UUID for the user.
   */
  id: Generated<string>;
  /**
   * URL to the user's profile image/avatar.
   */
  image: string | null;
  /**
   * Display name shown in the UI.
   */
  name: string;
  /**
   * Row last-updated timestamp (UTC).
   */
  updatedAt: Generated<Timestamp>;
}

export interface AuthVerification {
  /**
   * Row creation timestamp (UTC).
   */
  createdAt: Generated<Timestamp>;
  /**
   * When the verification challenge expires and is no longer valid.
   */
  expiresAt: Timestamp;
  /**
   * Primary key: UUID for the verification record.
   */
  id: Generated<string>;
  /**
   * Subject being verified (e.g., email address or user id).
   */
  identifier: string;
  /**
   * Row last-updated timestamp (UTC).
   */
  updatedAt: Generated<Timestamp>;
  /**
   * Opaque verification value (token, code).
   */
  value: string;
}

export interface CrmCampaignContacts {
  /**
   * FK to crm.campaigns(id).
   */
  campaignId: string;
  /**
   * FK to crm.contacts(id).
   */
  contactId: string;
  /**
   * Row creation timestamp (UTC).
   */
  createdAt: Generated<Timestamp>;
  /**
   * Primary key: UUID for the campaign-contact record.
   */
  id: Generated<string>;
  /**
   * Timestamp of the last engagement event.
   */
  interactionDate: Timestamp | null;
  /**
   * Engagement status for this contact.
   */
  status: CrmCampaignContactsStatus;
  /**
   * Row last-updated timestamp (UTC).
   */
  updatedAt: Generated<Timestamp>;
}

export interface CrmCampaigns {
  /**
   * Budget allocated to the campaign.
   */
  budget: Generated<Numeric | null>;
  /**
   * Row creation timestamp (UTC).
   */
  createdAt: Generated<Timestamp>;
  /**
   * Optional campaign description.
   */
  description: string | null;
  /**
   * Campaign end date (optional).
   */
  endDate: Timestamp | null;
  /**
   * Primary key: UUID for the campaign.
   */
  id: Generated<string>;
  /**
   * Campaign name.
   */
  name: string;
  /**
   * Campaign start date.
   */
  startDate: Timestamp;
  /**
   * Current campaign status.
   */
  status: CrmCampaignStatus;
  /**
   * Row last-updated timestamp (UTC).
   */
  updatedAt: Generated<Timestamp>;
}

export interface CrmCases {
  /**
   * When the case was closed (if applicable).
   */
  closedAt: Timestamp | null;
  /**
   * FK to crm.contacts(id) who opened/owns the case.
   */
  contactId: string | null;
  /**
   * Row creation timestamp (UTC).
   */
  createdAt: Generated<Timestamp>;
  /**
   * Detailed description of the case.
   */
  description: string;
  /**
   * Primary key: UUID for the case.
   */
  id: Generated<string>;
  /**
   * Priority level.
   */
  priority: CrmCasePriority;
  /**
   * Current status of the case.
   */
  status: CrmCaseStatus;
  /**
   * Case subject/title.
   */
  subject: string;
  /**
   * Row last-updated timestamp (UTC).
   */
  updatedAt: Generated<Timestamp>;
}

export interface CrmCompanies {
  /**
   * Row creation timestamp (UTC).
   */
  createdAt: Generated<Timestamp>;
  /**
   * Optional description/notes about the company.
   */
  description: string | null;
  /**
   * Primary contact email for the company.
   */
  email: string | null;
  /**
   * Primary key: UUID for the company.
   */
  id: Generated<string>;
  /**
   * Industry classification.
   */
  industry: string | null;
  /**
   * Unique company name.
   */
  name: string;
  /**
   * Main phone number for the company.
   */
  phoneNumber: string | null;
  /**
   * Row last-updated timestamp (UTC).
   */
  updatedAt: Generated<Timestamp>;
  /**
   * Company website URL.
   */
  website: string | null;
}

export interface CrmContacts {
  /**
   * Birth date of the contact (optional).
   */
  birthDate: Timestamp | null;
  /**
   * FK to crm.companies(id) if the contact is associated with a company.
   */
  companyId: string | null;
  /**
   * Row creation timestamp (UTC).
   */
  createdAt: Generated<Timestamp>;
  /**
   * Unique email address of the contact.
   */
  email: string;
  /**
   * Contact first name.
   */
  firstName: string;
  /**
   * Primary key: UUID for the contact.
   */
  id: Generated<string>;
  /**
   * Job title/role of the contact.
   */
  jobTitle: string | null;
  /**
   * Contact last name.
   */
  lastName: string;
  /**
   * Where this contact originated (e.g., referral, web, event).
   */
  leadSource: string | null;
  /**
   * Phone number of the contact.
   */
  phoneNumber: string | null;
  /**
   * Lifecycle status of the contact.
   */
  status: Generated<CrmContactStatus>;
  /**
   * Row last-updated timestamp (UTC).
   */
  updatedAt: Generated<Timestamp>;
}

export interface CrmInteractions {
  /**
   * FK to crm.contacts(id) if linked to a contact.
   */
  contactId: string | null;
  /**
   * Row creation timestamp (UTC).
   */
  createdAt: Generated<Timestamp>;
  /**
   * Detailed notes of the interaction.
   */
  description: string | null;
  /**
   * Primary key: UUID for the interaction record.
   */
  id: Generated<string>;
  /**
   * When the interaction occurred.
   */
  interactionDate: Timestamp;
  /**
   * FK to crm.opportunities(id) if linked to an opportunity.
   */
  opportunityId: string | null;
  /**
   * Subject or short title.
   */
  subject: string | null;
  /**
   * Interaction type.
   */
  type: CrmInteractionType;
  /**
   * Row last-updated timestamp (UTC).
   */
  updatedAt: Generated<Timestamp>;
}

export interface CrmInvoiceLineItems {
  /**
   * Row creation timestamp (UTC).
   */
  createdAt: Generated<Timestamp>;
  /**
   * Description of the billed item or service.
   */
  description: string;
  /**
   * Primary key: UUID for the line item.
   */
  id: Generated<string>;
  /**
   * FK to crm.invoices(id) this item belongs to.
   */
  invoiceId: string;
  /**
   * Computed total for the line = unit_price * quantity.
   */
  lineTotal: Generated<Numeric | null>;
  /**
   * Quantity for the item (must be > 0).
   */
  quantity: Generated<Numeric>;
  /**
   * Optional FK to lms.shipments(id) this charge relates to.
   */
  shipmentId: string | null;
  /**
   * Unit price for this item.
   */
  unitPrice: Numeric;
  /**
   * Row last-updated timestamp (UTC).
   */
  updatedAt: Generated<Timestamp>;
}

export interface CrmInvoices {
  /**
   * FK to crm.companies(id) for the billed company.
   */
  companyId: string | null;
  /**
   * FK to crm.contacts(id) for the billed contact.
   */
  contactId: string | null;
  /**
   * Row creation timestamp (UTC).
   */
  createdAt: Generated<Timestamp>;
  /**
   * ISO-4217 currency code.
   */
  currency: Generated<string>;
  /**
   * Payment due date.
   */
  dueDate: Timestamp;
  /**
   * Primary key: UUID for the invoice.
   */
  id: Generated<string>;
  /**
   * Date when the invoice was issued.
   */
  invoiceDate: Timestamp;
  /**
   * Unique invoice number (human-readable).
   */
  invoiceNumber: string;
  /**
   * Payment terms (e.g., Net-30).
   */
  paymentTerms: string | null;
  /**
   * Invoice lifecycle status (see crm.invoice_status).
   */
  status: CrmInvoiceStatus;
  /**
   * Subtotal amount before taxes.
   */
  subtotal: Numeric;
  /**
   * Tax amount applied to the invoice.
   */
  taxAmount: Generated<Numeric>;
  /**
   * Total amount billed (subtotal + taxes + adjustments).
   */
  totalAmount: Generated<Numeric>;
  /**
   * Row last-updated timestamp (UTC).
   */
  updatedAt: Generated<Timestamp>;
}

export interface CrmLeads {
  /**
   * Company name associated with the lead (free text).
   */
  companyName: string | null;
  /**
   * FK to crm.contacts(id) when this lead has been converted.
   */
  convertedToContactId: string | null;
  /**
   * Row creation timestamp (UTC).
   */
  createdAt: Generated<Timestamp>;
  /**
   * Unique email address of the lead.
   */
  email: string;
  /**
   * Lead first name.
   */
  firstName: string;
  /**
   * Primary key: UUID for the lead.
   */
  id: Generated<string>;
  /**
   * Lead last name.
   */
  lastName: string;
  /**
   * Numeric score indicating likelihood to convert.
   */
  leadScore: Generated<number>;
  /**
   * Where this lead originated (e.g., referral, web, event).
   */
  leadSource: string | null;
  /**
   * Lead pipeline status.
   */
  leadStatus: Generated<CrmLeadStatus>;
  /**
   * Phone number of the lead.
   */
  phoneNumber: string | null;
  /**
   * Row last-updated timestamp (UTC).
   */
  updatedAt: Generated<Timestamp>;
}

export interface CrmNotifications {
  /**
   * Channel used to deliver the notification.
   */
  channel: CrmNotificationChannel;
  /**
   * FK to crm.contacts(id) designated to receive the message.
   */
  contactId: string;
  /**
   * Row creation timestamp (UTC).
   */
  createdAt: Generated<Timestamp>;
  /**
   * Delivery result (pending/sent/delivered/failed/bounced).
   */
  deliveryStatus: CrmNotificationDeliveryStatus;
  /**
   * Primary key: UUID for the notification.
   */
  id: Generated<string>;
  /**
   * Message body (rendered content).
   */
  message: string;
  /**
   * Notification type/category.
   */
  notificationType: CrmNotificationType;
  /**
   * Recipient address/identifier (email/phone/webhook URL).
   */
  recipient: string;
  /**
   * Timestamp when the message was sent (if applicable).
   */
  sentAt: Timestamp | null;
  /**
   * FK to lms.shipments(id) that the notification concerns.
   */
  shipmentId: string;
  /**
   * Optional subject/title for the message (email-like).
   */
  subject: string | null;
  /**
   * Row last-updated timestamp (UTC).
   */
  updatedAt: Generated<Timestamp>;
}

export interface CrmOpportunities {
  /**
   * Expected revenue amount for the opportunity.
   */
  amount: Generated<Numeric>;
  /**
   * Planned/actual close date.
   */
  closeDate: Timestamp | null;
  /**
   * FK to crm.companies(id) representing the account.
   */
  companyId: string | null;
  /**
   * Row creation timestamp (UTC).
   */
  createdAt: Generated<Timestamp>;
  /**
   * Primary key: UUID for the opportunity.
   */
  id: Generated<string>;
  /**
   * Short name/label for the opportunity.
   */
  name: string;
  /**
   * FK to crm.contacts(id) for the primary contact.
   */
  primaryContactId: string | null;
  /**
   * Win probability percentage (0-100).
   */
  probability: Generated<Numeric>;
  /**
   * Sales pipeline stage.
   */
  stage: CrmOpportunityStage;
  /**
   * Row last-updated timestamp (UTC).
   */
  updatedAt: Generated<Timestamp>;
}

export interface CrmOpportunityProducts {
  /**
   * Row creation timestamp (UTC).
   */
  createdAt: Generated<Timestamp>;
  /**
   * Primary key: UUID for the line item.
   */
  id: Generated<string>;
  /**
   * FK to crm.opportunities(id).
   */
  opportunityId: string;
  /**
   * FK to crm.products(id).
   */
  productId: string;
  /**
   * Quantity of the product.
   */
  quantity: Generated<Numeric>;
  /**
   * Computed total = quantity * unit_price.
   */
  totalPrice: Generated<Numeric | null>;
  /**
   * Unit price applied for this line item (may differ from product base price).
   */
  unitPrice: Numeric;
  /**
   * Row last-updated timestamp (UTC).
   */
  updatedAt: Generated<Timestamp>;
}

export interface CrmProducts {
  /**
   * Row creation timestamp (UTC).
   */
  createdAt: Generated<Timestamp>;
  /**
   * Product description.
   */
  description: string | null;
  /**
   * Primary key: UUID for the product.
   */
  id: Generated<string>;
  /**
   * Unique product name.
   */
  name: string;
  /**
   * Base price for the product.
   */
  price: Numeric;
  /**
   * Stock-keeping unit code (unique).
   */
  sku: string | null;
  /**
   * Row last-updated timestamp (UTC).
   */
  updatedAt: Generated<Timestamp>;
}

export interface HdbCatalogHdbActionLog {
  actionName: string | null;
  createdAt: Generated<Timestamp>;
  errors: Json | null;
  id: Generated<string>;
  inputPayload: Json;
  requestHeaders: Json;
  responsePayload: Json | null;
  responseReceivedAt: Timestamp | null;
  sessionVariables: Json;
  status: string;
}

export interface HdbCatalogHdbCronEventInvocationLogs {
  createdAt: Generated<Timestamp | null>;
  eventId: string | null;
  id: Generated<string>;
  request: Json | null;
  response: Json | null;
  status: number | null;
}

export interface HdbCatalogHdbCronEvents {
  createdAt: Generated<Timestamp | null>;
  id: Generated<string>;
  nextRetryAt: Timestamp | null;
  scheduledTime: Timestamp;
  status: Generated<string>;
  tries: Generated<number>;
  triggerName: string;
}

export interface HdbCatalogHdbMetadata {
  id: number;
  metadata: Json;
  resourceVersion: Generated<number>;
}

export interface HdbCatalogHdbScheduledEventInvocationLogs {
  createdAt: Generated<Timestamp | null>;
  eventId: string | null;
  id: Generated<string>;
  request: Json | null;
  response: Json | null;
  status: number | null;
}

export interface HdbCatalogHdbScheduledEvents {
  comment: string | null;
  createdAt: Generated<Timestamp | null>;
  headerConf: Json | null;
  id: Generated<string>;
  nextRetryAt: Timestamp | null;
  payload: Json | null;
  retryConf: Json | null;
  scheduledTime: Timestamp;
  status: Generated<string>;
  tries: Generated<number>;
  webhookConf: Json;
}

export interface HdbCatalogHdbSchemaNotifications {
  id: number;
  instanceId: string;
  notification: Json;
  resourceVersion: Generated<number>;
  updatedAt: Generated<Timestamp | null>;
}

export interface HdbCatalogHdbVersion {
  cliState: Generated<Json>;
  consoleState: Generated<Json>;
  eeClientId: string | null;
  eeClientSecret: string | null;
  hasuraUuid: Generated<string>;
  upgradedOn: Timestamp;
  version: string;
}

export interface LmsAddresses {
  /**
   * Address line 1 (street, building, house number).
   */
  addressLine1: string;
  /**
   * Address line 2 (apartment, suite, unit). Optional.
   */
  addressLine2: string | null;
  /**
   * Intended usage of the address.
   */
  addressType: LmsAddressType;
  /**
   * City or locality.
   */
  city: string;
  /**
   * ISO 3166-1 alpha-3 (three-letter) country code.
   */
  country: string;
  /**
   * Row creation timestamp (UTC).
   */
  createdAt: Generated<Timestamp>;
  /**
   * Primary key: UUID for the address record.
   */
  id: Generated<string>;
  /**
   * Whether the address has been validated/standardized.
   */
  isValidated: Generated<boolean>;
  /**
   * Latitude in decimal degrees; part of unique pair (latitude, longitude) to prevent duplicate geocoded points.
   */
  latitude: Numeric | null;
  /**
   * Longitude in decimal degrees; part of unique pair (latitude, longitude) to prevent duplicate geocoded points.
   */
  longitude: Numeric | null;
  /**
   * ZIP/postal code.
   */
  postalCode: string;
  /**
   * State, province, or region.
   */
  state: string;
  /**
   * Row last-updated timestamp (UTC).
   */
  updatedAt: Generated<Timestamp>;
}

export interface LmsPackages {
  /**
   * Short description of package contents.
   */
  contentsDescription: string | null;
  /**
   * Row creation timestamp (UTC).
   */
  createdAt: Generated<Timestamp>;
  /**
   * Declared value for customs/insurance.
   */
  declaredValue: Numeric | null;
  /**
   * Height (cm).
   */
  height: Numeric | null;
  /**
   * Primary key: UUID for the package.
   */
  id: Generated<string>;
  /**
   * Length (cm).
   */
  length: Numeric | null;
  /**
   * Shipment-local identifier for the package (unique per shipment).
   */
  packageNumber: string;
  /**
   * Packaging type (see lms.package_type).
   */
  packageType: LmsPackageType;
  /**
   * FK to lms.shipments(id).
   */
  shipmentId: string;
  /**
   * Row last-updated timestamp (UTC).
   */
  updatedAt: Generated<Timestamp>;
  /**
   * Weight of the package (kg).
   */
  weight: Numeric;
  /**
   * Width (cm).
   */
  width: Numeric | null;
}

export interface LmsPricingRates {
  /**
   * Base rate component.
   */
  baseRate: Numeric;
  /**
   * Row creation timestamp (UTC).
   */
  createdAt: Generated<Timestamp>;
  /**
   * FK to lms.pricing_zones(id) for destination.
   */
  destinationZoneId: string;
  /**
   * Date when this rate becomes effective.
   */
  effectiveDate: Timestamp;
  effectiveRange: Generated<string | null>;
  /**
   * Date when this rate expires (optional).
   */
  expiryDate: Timestamp | null;
  /**
   * Fuel surcharge percentage.
   */
  fuelSurchargeRate: Generated<Numeric | null>;
  /**
   * Primary key: UUID for the rate row.
   */
  id: Generated<string>;
  /**
   * FK to lms.pricing_zones(id) for origin.
   */
  originZoneId: string;
  /**
   * Per-kilogram rate component.
   */
  perKgRate: Numeric;
  /**
   * FK to lms.shipping_services(id).
   */
  serviceId: string;
  /**
   * Row last-updated timestamp (UTC).
   */
  updatedAt: Generated<Timestamp>;
  /**
   * Maximum weight for the bracket (kg).
   */
  weightMax: Numeric;
  /**
   * Minimum weight for the bracket (kg).
   */
  weightMin: Numeric;
  weightRange: Generated<string | null>;
}

export interface LmsPricingZoneCountries {
  /**
   * ISO-3166-1 alpha-3 country code belonging to the zone.
   */
  countryCode: string;
  /**
   * Row creation timestamp (UTC).
   */
  createdAt: Generated<Timestamp>;
  /**
   * Primary key: UUID for the mapping row.
   */
  id: Generated<string>;
  /**
   * FK to lms.pricing_zones(id).
   */
  pricingZoneId: string;
}

export interface LmsPricingZones {
  /**
   * Row creation timestamp (UTC).
   */
  createdAt: Generated<Timestamp>;
  /**
   * Primary key: UUID for the pricing zone.
   */
  id: Generated<string>;
  /**
   * Human-readable name for the zone.
   */
  name: string;
  /**
   * Row last-updated timestamp (UTC).
   */
  updatedAt: Generated<Timestamp>;
  /**
   * Short unique code for the zone.
   */
  zoneCode: string;
}

export interface LmsProviderInvoiceLineItems {
  /**
   * Row creation timestamp (UTC).
   */
  createdAt: Generated<Timestamp>;
  /**
   * Description of the charge.
   */
  description: string;
  /**
   * Primary key: UUID for the line item.
   */
  id: Generated<string>;
  /**
   * Computed total = unit_price * quantity.
   */
  lineTotal: Generated<Numeric | null>;
  /**
   * FK to lms.provider_invoices(id).
   */
  providerInvoiceId: string;
  /**
   * Quantity (must be > 0).
   */
  quantity: Generated<number>;
  transportLegId: string | null;
  /**
   * Unit price.
   */
  unitPrice: Numeric;
  /**
   * Row last-updated timestamp (UTC).
   */
  updatedAt: Generated<Timestamp>;
}

export interface LmsProviderInvoices {
  /**
   * Row creation timestamp (UTC).
   */
  createdAt: Generated<Timestamp>;
  /**
   * ISO-4217 currency code.
   */
  currency: Generated<string>;
  /**
   * Payment due date.
   */
  dueDate: Timestamp;
  /**
   * Primary key: UUID for the invoice.
   */
  id: Generated<string>;
  /**
   * Invoice issue date.
   */
  invoiceDate: Timestamp;
  /**
   * Unique invoice number within the provider.
   */
  invoiceNumber: string;
  /**
   * Date when payment was made.
   */
  paymentDate: Timestamp | null;
  /**
   * FK to lms.transportation_providers(id).
   */
  providerId: string;
  /**
   * Invoice status (see lms.provider_invoice_status).
   */
  status: Generated<LmsProviderInvoiceStatus>;
  /**
   * Subtotal amount before taxes.
   */
  subtotal: Numeric;
  /**
   * Tax amount.
   */
  taxAmount: Generated<Numeric | null>;
  /**
   * Computed total = subtotal + tax_amount.
   */
  totalAmount: Generated<Numeric | null>;
  /**
   * Row last-updated timestamp (UTC).
   */
  updatedAt: Generated<Timestamp>;
}

export interface LmsProviderPerformance {
  /**
   * Row creation timestamp (UTC).
   */
  createdAt: Generated<Timestamp>;
  /**
   * Primary key: UUID for the performance row.
   */
  id: Generated<string>;
  /**
   * When the metric was measured.
   */
  measurementDate: Timestamp;
  /**
   * Metric category (see lms.performance_metric_type).
   */
  metricType: LmsPerformanceMetricType;
  /**
   * Numeric value of the metric.
   */
  metricValue: Numeric | null;
  /**
   * Optional notes/details.
   */
  notes: string | null;
  /**
   * FK to lms.transportation_providers(id).
   */
  providerId: string;
  /**
   * FK to lms.shipments(id).
   */
  shipmentId: string;
  transportLegId: string | null;
  /**
   * Row last-updated timestamp (UTC).
   */
  updatedAt: Generated<Timestamp>;
}

export interface LmsProviderRates {
  /**
   * Base rate component.
   */
  baseRate: Numeric;
  /**
   * Row creation timestamp (UTC).
   */
  createdAt: Generated<Timestamp>;
  /**
   * ISO-4217 currency code.
   */
  currency: Generated<string>;
  /**
   * FK to lms.pricing_zones(id) for destination.
   */
  destinationZoneId: string;
  /**
   * Date when this rate becomes effective.
   */
  effectiveDate: Timestamp;
  effectiveRange: Generated<string | null>;
  /**
   * Date when this rate expires (optional).
   */
  expiryDate: Timestamp | null;
  /**
   * Fuel surcharge percentage.
   */
  fuelSurchargeRate: Generated<Numeric | null>;
  /**
   * Primary key: UUID for the provider rate row.
   */
  id: Generated<string>;
  /**
   * FK to lms.pricing_zones(id) for origin.
   */
  originZoneId: string;
  /**
   * Per-kilogram rate component.
   */
  perKgRate: Numeric;
  /**
   * FK to lms.provider_services(id).
   */
  providerServiceId: string;
  /**
   * Row last-updated timestamp (UTC).
   */
  updatedAt: Generated<Timestamp>;
  /**
   * Maximum weight for the bracket (kg).
   */
  weightMax: Numeric;
  /**
   * Minimum weight for the bracket (kg).
   */
  weightMin: Numeric;
  weightRange: Generated<string | null>;
}

export interface LmsProviderServiceDestinationCountries {
  /**
   * ISO-3166-1 alpha-3 destination country code.
   */
  countryCode: string;
  /**
   * Row creation timestamp (UTC).
   */
  createdAt: Generated<Timestamp>;
  /**
   * Primary key: UUID for the destination mapping.
   */
  id: Generated<string>;
  /**
   * FK to lms.provider_services(id).
   */
  providerServiceId: string;
}

export interface LmsProviderServiceMaxDimensions {
  /**
   * Row creation timestamp (UTC).
   */
  createdAt: Generated<Timestamp>;
  /**
   * Max height (cm).
   */
  height: Numeric | null;
  /**
   * Primary key: UUID for the record.
   */
  id: Generated<string>;
  /**
   * Max length (cm).
   */
  length: Numeric | null;
  /**
   * FK to lms.provider_services(id).
   */
  providerServiceId: string;
  /**
   * Max width (cm).
   */
  width: Numeric | null;
}

export interface LmsProviderServiceOriginCountries {
  /**
   * ISO-3166-1 alpha-3 origin country code.
   */
  countryCode: string;
  /**
   * Row creation timestamp (UTC).
   */
  createdAt: Generated<Timestamp>;
  /**
   * Primary key: UUID for the origin mapping.
   */
  id: Generated<string>;
  /**
   * FK to lms.provider_services(id).
   */
  providerServiceId: string;
}

export interface LmsProviderServices {
  /**
   * Row creation timestamp (UTC).
   */
  createdAt: Generated<Timestamp>;
  /**
   * Latest time for same-day processing.
   */
  cutoffTime: string | null;
  /**
   * Primary key: UUID for the provider service.
   */
  id: Generated<string>;
  /**
   * Whether insurance is available.
   */
  insuranceAvailable: Generated<boolean>;
  /**
   * Whether the provider service is active.
   */
  isActive: Generated<boolean>;
  /**
   * Max allowed weight for this provider service.
   */
  maxWeight: Numeric | null;
  /**
   * FK to lms.transportation_providers(id).
   */
  providerId: string;
  /**
   * Display name for the provider-specific service.
   */
  serviceName: string;
  /**
   * Service type (see lms.service_type).
   */
  serviceType: LmsServiceType;
  /**
   * Whether tracking is supported by provider.
   */
  trackingAvailable: Generated<boolean>;
  /**
   * Estimated maximum transit time (days).
   */
  transitTimeMax: number | null;
  /**
   * Estimated minimum transit time (days).
   */
  transitTimeMin: number | null;
  /**
   * Transport mode used by the service.
   */
  transportMode: LmsTransportMode;
  /**
   * Row last-updated timestamp (UTC).
   */
  updatedAt: Generated<Timestamp>;
}

export interface LmsRoutes {
  /**
   * Actual arrival timestamp.
   */
  actualArrival: Timestamp | null;
  /**
   * Actual departure timestamp.
   */
  actualDeparture: Timestamp | null;
  /**
   * Row creation timestamp (UTC).
   */
  createdAt: Generated<Timestamp>;
  /**
   * FK to tms.drivers(id) assigned to this route.
   */
  driverId: string | null;
  /**
   * Planned arrival timestamp.
   */
  estimatedArrival: Timestamp | null;
  /**
   * Planned departure timestamp.
   */
  estimatedDeparture: Timestamp | null;
  /**
   * Primary key: UUID for the route.
   */
  id: Generated<string>;
  /**
   * Date of the route.
   */
  routeDate: Timestamp;
  /**
   * Route display name or code.
   */
  routeName: string;
  /**
   * Current route status.
   */
  status: LmsRouteStatus;
  /**
   * Row last-updated timestamp (UTC).
   */
  updatedAt: Generated<Timestamp>;
  /**
   * FK to tms.vehicles(id) used for this route.
   */
  vehicleId: string | null;
}

export interface LmsRouteShipments {
  /**
   * Actual delivery timestamp.
   */
  actualDelivery: Timestamp | null;
  /**
   * Row creation timestamp (UTC).
   */
  createdAt: Generated<Timestamp>;
  /**
   * Planned delivery date for the stop.
   */
  deliveryDate: Timestamp;
  /**
   * Per-shipment delivery status while on route.
   */
  deliveryStatus: LmsDeliveryStatus;
  /**
   * Planned delivery timestamp.
   */
  estimatedDelivery: Timestamp | null;
  /**
   * Primary key: UUID for the route-shipment mapping.
   */
  id: Generated<string>;
  /**
   * Recipient name/signature captured.
   */
  recipientSignature: string | null;
  /**
   * FK to lms.routes(id).
   */
  routeId: string;
  /**
   * Order of delivery for this shipment on the route.
   */
  sequenceNumber: number;
  /**
   * FK to lms.shipments(id).
   */
  shipmentId: string;
  /**
   * Whether recipient signature is required.
   */
  signatureRequired: Generated<boolean>;
  /**
   * Row last-updated timestamp (UTC).
   */
  updatedAt: Generated<Timestamp>;
}

export interface LmsShipments {
  /**
   * Row creation timestamp (UTC).
   */
  createdAt: Generated<Timestamp>;
  /**
   * FK to auth.users(id) who created the shipment.
   */
  createdBy: string | null;
  /**
   * ISO-4217 currency code.
   */
  currency: Generated<string>;
  /**
   * Delivery date (actual).
   */
  deliveryDate: Timestamp | null;
  /**
   * Estimated delivery date.
   */
  estimatedDeliveryDate: Timestamp | null;
  /**
   * Primary key: UUID for the shipment.
   */
  id: Generated<string>;
  /**
   * Insurance amount for the shipment (optional).
   */
  insuranceAmount: Numeric | null;
  /**
   * Pickup date (planned or actual).
   */
  pickupDate: Timestamp | null;
  /**
   * Primary transport mode (air/sea/road/rail).
   */
  primaryTransportMode: LmsTransportMode;
  /**
   * FK to lms.addresses(id) for delivery destination.
   */
  receiverAddressId: string;
  /**
   * FK to crm.companies(id) for the receiver company.
   */
  receiverCompanyId: string | null;
  /**
   * FK to crm.contacts(id) for the receiver contact.
   */
  receiverContactId: string | null;
  /**
   * FK to lms.addresses(id) for pickup origin.
   */
  senderAddressId: string;
  /**
   * FK to crm.companies(id) for the sender company.
   */
  senderCompanyId: string | null;
  /**
   * FK to crm.contacts(id) for the sender contact.
   */
  senderContactId: string | null;
  /**
   * FK to lms.shipping_services(id) used for rating/booking.
   */
  serviceId: string;
  /**
   * Rated shipping cost (optional).
   */
  shippingCost: Numeric | null;
  /**
   * Special handling instructions.
   */
  specialInstructions: string | null;
  /**
   * Current shipment status.
   */
  status: LmsShipmentStatus;
  /**
   * Declared total value of the shipment.
   */
  totalValue: Numeric | null;
  /**
   * Total shipment weight (kg).
   */
  totalWeight: Numeric;
  /**
   * Unique tracking number.
   */
  trackingNumber: string;
  /**
   * Row last-updated timestamp (UTC).
   */
  updatedAt: Generated<Timestamp>;
}

export interface LmsShippingServiceMaxDimensions {
  /**
   * Row creation timestamp (UTC).
   */
  createdAt: Generated<Timestamp>;
  /**
   * Max height allowed (cm by default).
   */
  height: Numeric | null;
  /**
   * Primary key: UUID for the record.
   */
  id: Generated<string>;
  /**
   * Max length allowed (cm by default).
   */
  length: Numeric | null;
  /**
   * FK to lms.shipping_services(id).
   */
  shippingServiceId: string;
  /**
   * Max width allowed (cm by default).
   */
  width: Numeric | null;
}

export interface LmsShippingServices {
  /**
   * Row creation timestamp (UTC).
   */
  createdAt: Generated<Timestamp>;
  /**
   * Estimated maximum delivery time (days).
   */
  deliveryTimeMax: number | null;
  /**
   * Estimated minimum delivery time (days).
   */
  deliveryTimeMin: number | null;
  /**
   * Optional service description.
   */
  description: string | null;
  /**
   * Primary key: UUID for the shipping service.
   */
  id: Generated<string>;
  /**
   * Whether this service is currently available.
   */
  isActive: Generated<boolean>;
  /**
   * Max allowed weight for this service (kg by default).
   */
  maxWeight: Numeric | null;
  /**
   * Service display name (unique).
   */
  name: string;
  /**
   * Service category (see lms.service_type).
   */
  serviceType: LmsServiceType;
  /**
   * Row last-updated timestamp (UTC).
   */
  updatedAt: Generated<Timestamp>;
}

export interface LmsTrackingEvents {
  /**
   * Row creation timestamp (UTC).
   */
  createdAt: Generated<Timestamp>;
  /**
   * Short description/details of the event.
   */
  eventDescription: string;
  /**
   * Optional free-text location for the event.
   */
  eventLocation: string | null;
  /**
   * When the event occurred.
   */
  eventTimestamp: Timestamp;
  /**
   * Event type (see lms.tracking_event_type).
   */
  eventType: LmsTrackingEventType;
  /**
   * Primary key: UUID for the event.
   */
  id: Generated<string>;
  /**
   * FK to lms.shipments(id).
   */
  shipmentId: string;
  /**
   * Row last-updated timestamp (UTC).
   */
  updatedAt: Generated<Timestamp>;
}

export interface LmsTransportationProviders {
  /**
   * FK to lms.addresses(id).
   */
  addressId: string | null;
  /**
   * API endpoint URL for provider integration.
   */
  apiEndpoint: string | null;
  /**
   * API key/secret for provider integration.
   */
  apiKey: string | null;
  /**
   * Legal/trading name of the provider.
   */
  companyName: string;
  /**
   * Primary contact person name.
   */
  contactPerson: string | null;
  /**
   * Contract end/renewal date.
   */
  contractEndDate: Timestamp | null;
  /**
   * Contract start date.
   */
  contractStartDate: Timestamp | null;
  /**
   * Row creation timestamp (UTC).
   */
  createdAt: Generated<Timestamp>;
  /**
   * Contact email address.
   */
  email: string | null;
  /**
   * Primary key: UUID for the provider.
   */
  id: Generated<string>;
  /**
   * Coverage amount for provider liability insurance.
   */
  insuranceCoverage: Numeric | null;
  /**
   * Whether the provider is currently active.
   */
  isActive: Generated<boolean>;
  /**
   * Payment terms (e.g., Net-30).
   */
  paymentTerms: string | null;
  /**
   * Aggregate performance rating (0-5).
   */
  performanceRating: Numeric | null;
  /**
   * Contact phone number.
   */
  phoneNumber: string | null;
  /**
   * Provider category (see lms.provider_type).
   */
  providerType: LmsProviderType;
  /**
   * Row last-updated timestamp (UTC).
   */
  updatedAt: Generated<Timestamp>;
}

export interface LmsTransportLegs {
  /**
   * Actual delivery timestamp.
   */
  actualDelivery: Timestamp | null;
  /**
   * Actual pickup timestamp.
   */
  actualPickup: Timestamp | null;
  /**
   * Cost attributed to this leg.
   */
  cost: Numeric | null;
  /**
   * Row creation timestamp (UTC).
   */
  createdAt: Generated<Timestamp>;
  /**
   * ISO-4217 currency code for the leg cost.
   */
  currency: Generated<string | null>;
  /**
   * FK to lms.addresses(id) destination (optional).
   */
  destinationAddressId: string | null;
  /**
   * FK to lms.warehouses(id) destination (optional).
   */
  destinationWarehouseId: string | null;
  /**
   * FK to tms.drivers(id) assigned to this leg (if applicable).
   */
  driverId: string | null;
  /**
   * Primary key: UUID for the transport leg.
   */
  id: Generated<string>;
  /**
   * Sequence number within the shipment (starts at 1).
   */
  legSequence: number;
  /**
   * FK to lms.addresses(id) origin (optional).
   */
  originAddressId: string | null;
  /**
   * FK to lms.warehouses(id) origin (optional).
   */
  originWarehouseId: string | null;
  /**
   * FK to lms.transportation_providers(id).
   */
  providerId: string | null;
  /**
   * FK to lms.provider_services(id).
   */
  providerServiceId: string | null;
  /**
   * Tracking number at the provider level (optional).
   */
  providerTrackingNumber: string | null;
  /**
   * Planned delivery timestamp.
   */
  scheduledDelivery: Timestamp | null;
  /**
   * Planned pickup timestamp.
   */
  scheduledPickup: Timestamp | null;
  /**
   * FK to lms.shipments(id).
   */
  shipmentId: string;
  /**
   * Special handling or notes for this leg.
   */
  specialInstructions: string | null;
  /**
   * Current status of the leg.
   */
  status: LmsLegStatus;
  /**
   * Type of leg (pickup/linehaul/delivery/transfer).
   */
  transportType: LmsTransportLegType;
  /**
   * Row last-updated timestamp (UTC).
   */
  updatedAt: Generated<Timestamp>;
  /**
   * FK to tms.vehicles(id) used for this leg (if applicable).
   */
  vehicleId: string | null;
}

export interface LmsWarehouseInventories {
  /**
   * When the package arrived at the warehouse.
   */
  arrivedAt: Timestamp | null;
  /**
   * Row creation timestamp (UTC).
   */
  createdAt: Generated<Timestamp>;
  /**
   * When the package departed the warehouse.
   */
  departedAt: Timestamp | null;
  /**
   * Primary key: UUID for the inventory record.
   */
  id: Generated<string>;
  /**
   * Optional location/shelf/bin code inside the warehouse.
   */
  locationCode: string | null;
  /**
   * FK to lms.packages(id).
   */
  packageId: string;
  /**
   * FK to lms.shipments(id).
   */
  shipmentId: string;
  /**
   * Inventory status (see lms.warehouse_inventory_status).
   */
  status: LmsWarehouseInventoryStatus;
  /**
   * Row last-updated timestamp (UTC).
   */
  updatedAt: Generated<Timestamp>;
  /**
   * FK to lms.warehouses(id).
   */
  warehouseId: string;
}

export interface LmsWarehouses {
  /**
   * FK to lms.addresses(id).
   */
  addressId: string;
  /**
   * Optional capacity number (unit depends on org policy).
   */
  capacity: number | null;
  /**
   * Short unique code for the warehouse.
   */
  code: string;
  /**
   * Row creation timestamp (UTC).
   */
  createdAt: Generated<Timestamp>;
  /**
   * Primary key: UUID for the warehouse.
   */
  id: Generated<string>;
  /**
   * Whether the warehouse is active.
   */
  isActive: Generated<boolean>;
  /**
   * FK to auth.users(id) managing this warehouse.
   */
  managerId: string | null;
  /**
   * Warehouse display name.
   */
  name: string;
  /**
   * Row last-updated timestamp (UTC).
   */
  updatedAt: Generated<Timestamp>;
  /**
   * Warehouse type (see lms.warehouse_type).
   */
  warehouseType: LmsWarehouseType;
}

export interface OrgOrganization {
  /**
   * Row creation timestamp (UTC).
   */
  createdAt: Generated<Timestamp>;
  /**
   * Primary key: UUID for the organization.
   */
  id: Generated<string>;
  /**
   * Human-readable organization name.
   */
  name: string;
  /**
   * FK to auth.users(id) designating the org owner.
   */
  ownerId: string;
  /**
   * Row last-updated timestamp (UTC).
   */
  updatedAt: Generated<Timestamp>;
}

export interface OrgRoleActions {
  /**
   * Permitted action from org.permission_actions.
   */
  action: OrgPermissionActions;
  /**
   * Row creation timestamp (UTC).
   */
  createdAt: Generated<Timestamp>;
  /**
   * Primary key: UUID for the role-action grant.
   */
  id: Generated<string>;
  /**
   * FK to org.roles(id).
   */
  roleId: string;
  /**
   * Row last-updated timestamp (UTC).
   */
  updatedAt: Generated<Timestamp>;
}

export interface OrgRoles {
  /**
   * Row creation timestamp (UTC).
   */
  createdAt: Generated<Timestamp>;
  /**
   * Optional role description.
   */
  description: string | null;
  /**
   * Primary key: UUID for the role.
   */
  id: Generated<string>;
  /**
   * Role name (e.g., admin, member).
   */
  name: string;
  /**
   * FK to org.organization(id) that owns this role.
   */
  orgId: string;
  /**
   * Row last-updated timestamp (UTC).
   */
  updatedAt: Generated<Timestamp>;
}

export interface OrgTeamMembers {
  /**
   * Row creation timestamp (UTC).
   */
  createdAt: Generated<Timestamp>;
  /**
   * Primary key: UUID for the membership record.
   */
  id: Generated<string>;
  /**
   * FK to org.teams(id).
   */
  teamId: string;
  /**
   * Row last-updated timestamp (UTC).
   */
  updatedAt: Generated<Timestamp>;
  /**
   * FK to auth.users(id).
   */
  userId: string;
}

export interface OrgTeamResouces {
  /**
   * Row creation timestamp (UTC).
   */
  createdAt: Generated<Timestamp>;
  /**
   * Primary key: UUID for the resource.
   */
  id: Generated<string>;
  /**
   * Resource identifier string.
   */
  resource: string;
  /**
   * Row last-updated timestamp (UTC).
   */
  updatedAt: Generated<Timestamp>;
}

export interface OrgTeamRoles {
  /**
   * FK to org.roles(id).
   */
  roleId: string;
  /**
   * FK to org.teams(id).
   */
  teamId: string;
}

export interface OrgTeams {
  /**
   * Row creation timestamp (UTC).
   */
  createdAt: Generated<Timestamp>;
  /**
   * Optional team description.
   */
  description: string | null;
  /**
   * Primary key: UUID for the team.
   */
  id: Generated<string>;
  /**
   * Team name.
   */
  name: string;
  /**
   * FK to org.organization(id) that owns this team.
   */
  orgId: string;
  /**
   * Row last-updated timestamp (UTC).
   */
  updatedAt: Generated<Timestamp>;
}

export interface TmsDrivers {
  /**
   * Row creation timestamp (UTC).
   */
  createdAt: Generated<Timestamp>;
  /**
   * Contact email address (unique).
   */
  email: string;
  /**
   * Internal employee identifier (unique).
   */
  employeeId: string;
  /**
   * Driver first name.
   */
  firstName: string;
  /**
   * Date the driver was hired.
   */
  hireDate: Timestamp;
  /**
   * Primary key: UUID for the driver.
   */
  id: Generated<string>;
  /**
   * Driver last name.
   */
  lastName: string;
  /**
   * Government driver's license number (unique).
   */
  licenseNumber: string;
  /**
   * Contact phone number for the driver.
   */
  phoneNumber: string;
  /**
   * Current driver status (see tms.driver_status).
   */
  status: TmsDriverStatus;
  /**
   * Row last-updated timestamp (UTC).
   */
  updatedAt: Generated<Timestamp>;
}

export interface TmsVehicles {
  /**
   * Volume capacity in cubic meters (or configured unit).
   */
  capacityVolume: Numeric | null;
  /**
   * Weight capacity in kilograms (or configured unit).
   */
  capacityWeight: Numeric | null;
  /**
   * Row creation timestamp (UTC).
   */
  createdAt: Generated<Timestamp>;
  /**
   * Primary key: UUID for the vehicle.
   */
  id: Generated<string>;
  /**
   * License plate number (unique).
   */
  licensePlate: string;
  /**
   * Vehicle manufacturer (make).
   */
  make: string;
  /**
   * Vehicle model.
   */
  model: string;
  /**
   * Current operational status.
   */
  status: TmsVehicleStatus;
  /**
   * Row last-updated timestamp (UTC).
   */
  updatedAt: Generated<Timestamp>;
  /**
   * Internal vehicle identifier (unique).
   */
  vehicleNumber: string;
  /**
   * Vehicle type (see tms.vehicle_type).
   */
  vehicleType: TmsVehicleType;
  /**
   * Model year; constrained to a reasonable range.
   */
  year: number;
}

export interface DB {
  _SqlxMigrations: _SqlxMigrations;
  "auth.accounts": AuthAccounts;
  "auth.sessions": AuthSessions;
  "auth.users": AuthUsers;
  "auth.verification": AuthVerification;
  "crm.campaignContacts": CrmCampaignContacts;
  "crm.campaigns": CrmCampaigns;
  "crm.cases": CrmCases;
  "crm.companies": CrmCompanies;
  "crm.contacts": CrmContacts;
  "crm.interactions": CrmInteractions;
  "crm.invoiceLineItems": CrmInvoiceLineItems;
  "crm.invoices": CrmInvoices;
  "crm.leads": CrmLeads;
  "crm.notifications": CrmNotifications;
  "crm.opportunities": CrmOpportunities;
  "crm.opportunityProducts": CrmOpportunityProducts;
  "crm.products": CrmProducts;
  "hdbCatalog.hdbActionLog": HdbCatalogHdbActionLog;
  "hdbCatalog.hdbCronEventInvocationLogs": HdbCatalogHdbCronEventInvocationLogs;
  "hdbCatalog.hdbCronEvents": HdbCatalogHdbCronEvents;
  "hdbCatalog.hdbMetadata": HdbCatalogHdbMetadata;
  "hdbCatalog.hdbScheduledEventInvocationLogs": HdbCatalogHdbScheduledEventInvocationLogs;
  "hdbCatalog.hdbScheduledEvents": HdbCatalogHdbScheduledEvents;
  "hdbCatalog.hdbSchemaNotifications": HdbCatalogHdbSchemaNotifications;
  "hdbCatalog.hdbVersion": HdbCatalogHdbVersion;
  "lms.addresses": LmsAddresses;
  "lms.packages": LmsPackages;
  "lms.pricingRates": LmsPricingRates;
  "lms.pricingZoneCountries": LmsPricingZoneCountries;
  "lms.pricingZones": LmsPricingZones;
  "lms.providerInvoiceLineItems": LmsProviderInvoiceLineItems;
  "lms.providerInvoices": LmsProviderInvoices;
  "lms.providerPerformance": LmsProviderPerformance;
  "lms.providerRates": LmsProviderRates;
  "lms.providerServiceDestinationCountries": LmsProviderServiceDestinationCountries;
  "lms.providerServiceMaxDimensions": LmsProviderServiceMaxDimensions;
  "lms.providerServiceOriginCountries": LmsProviderServiceOriginCountries;
  "lms.providerServices": LmsProviderServices;
  "lms.routes": LmsRoutes;
  "lms.routeShipments": LmsRouteShipments;
  "lms.shipments": LmsShipments;
  "lms.shippingServiceMaxDimensions": LmsShippingServiceMaxDimensions;
  "lms.shippingServices": LmsShippingServices;
  "lms.trackingEvents": LmsTrackingEvents;
  "lms.transportationProviders": LmsTransportationProviders;
  "lms.transportLegs": LmsTransportLegs;
  "lms.warehouseInventories": LmsWarehouseInventories;
  "lms.warehouses": LmsWarehouses;
  "org.organization": OrgOrganization;
  "org.roleActions": OrgRoleActions;
  "org.roles": OrgRoles;
  "org.teamMembers": OrgTeamMembers;
  "org.teamResouces": OrgTeamResouces;
  "org.teamRoles": OrgTeamRoles;
  "org.teams": OrgTeams;
  "tms.drivers": TmsDrivers;
  "tms.vehicles": TmsVehicles;
}
